// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "antialiastool.h"

// Dispatch interfaces referenced by this interface
#include "FilterItems.h"


/////////////////////////////////////////////////////////////////////////////
// CAntiAliasTool properties

/////////////////////////////////////////////////////////////////////////////
// CAntiAliasTool operations

LPUNKNOWN CAntiAliasTool::GetBitmap()
{
	LPUNKNOWN result;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}

CFilterItems CAntiAliasTool::GetFilters()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xcc, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CFilterItems(pDispatch);
}

BOOL CAntiAliasTool::GetAntialias()
{
	BOOL result;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAntiAliasTool::SetAntialias(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xc9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}
